---
- name: install basic desktop
  ansible.builtin.package:
    name:
      - xorg-x11-server-Xorg
      - xorg-x11-xinit
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - make
      - gcc
      - mesa-dri-drivers
      - htop
    state: present
  become: yes
