- name: mail with mutt
  package:
    name:
      - neomutt
      - isync     # sync mail to local storage
      - lynx      # display html
      - notmuch   # search mail
      - msmtp     # send mail
  become: true

- name: create mail directory if it does not exist
  ansible.builtin.file:
    path: $HOME/.mail
    state: directory
    mode: '0755'
