---
- name: install packages
  package:
    name:
      - qutebrowser
      - qt5-qtwebengine-freeworld   # video codecs
    state: present
  become: true


- name: install python packages
  pip:
    name:
      - tldextract # qutebrowser: bitwarden userscript
    state: present

