#!/bin/bash

#:bind o spawn --userscript /path/to/userscripts/qutedmenu open
#:bind O spawn --userscript /path/to/userscripts/qutedmenu tab

QUTE_DATA_DIR=$HOME/.local/share/qutebrowser

create_menu() {
        printf -- '%s\n' "$(
		sqlite3 -separator ' ' "$QUTE_DATA_DIR/history.sqlite" \
		'SELECT title, url from CompletionHistory ORDER BY last_atime DESC')"
	}

get_selection() {
    opts+=(-p qutebrowser)
    create_menu | rofi -dmenu -l 10 "${opts[@]}"
}

url=$(get_selection)
url=${url/*http/http}

# if no selection is made, exit (escape pressed, e.g.)
[[ -z $url ]] && exit 0

case $1 in
    open)    printf '%s' "open $url" >> "$QUTE_FIFO" || qutebrowser "$url" ;;
    tab)     printf '%s' "open -t $url" >> "$QUTE_FIFO" || qutebrowser "$url"  ;;
esac
