#!/bin/bash

# Modification of:
# https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qutedmenu

QUTE_DATA_DIR=$HOME/.local/share/qutebrowser
QUTE_BOOKMARKS_DIR=$HOME/nextcloud/apps/qutebrowser

create_menu() {
        printf -- '%s\n' "$(
		sqlite3 -separator ' ' "$QUTE_DATA_DIR/history.sqlite" \
		'SELECT title, url from CompletionHistory ORDER BY last_atime DESC')"
	}

create_menu_quickmarks() {
    # Check quickmarks
    while read -r mark; do
        printf -- '%s\n' "$mark"
    done < "$QUTE_BOOKMARKS_DIR"/bookmarks
}

case $1 in
	open | tab)
		get_history() {
			opts+=(-p qutebrowser)
			create_menu | rofi -dmenu -i -l 8 "${opts[@]}"
		};;
	marks | marks-tab)
	get_history() {
		opts+=(-p qutebrowser)
		create_menu_quickmarks | rofi -dmenu -i -l 8 "${opts[@]}"
	};;
esac

url=$(get_history)
url=${url/*http/http}

# if no selection is made, exit (escape pressed, e.g.)
[[ -z $url ]] && exit 0

case $1 in
    open)    
		printf '%s' "open $url" >> "$QUTE_FIFO" || qutebrowser "$url" --target tab-bg ;;
    tab)     
		printf '%s' "open -t $url" >> "$QUTE_FIFO" || qutebrowser "$url"  ;;
	marks)
		printf '%s' "open $url" >> "$QUTE_FIFO" || qutebrowser "$url"  ;;
	marks-tab)
		printf '%s' "open -t $url" >> "$QUTE_FIFO" || qutebrowser "$url"  ;;
esac
