---

# Ansible
# Git
# SSH

- hosts: localhost
  # roles:
  #   - xorg
  #   - suckless
  #   - general

  tasks:
  - name: create .local/bin directory
    file:
      path: ~/.local/bin
      state: directory

  - name: install basic desktop
    package:
      name:
        - xorg-x11-server-Xorg
        - xorg-x11-xinit
        - libX11-devel
        - libXft-devel
        - libXinerama-devel
        - make
        - gcc
        - mesa-dri-drivers
        - xsetroot
      state: present
    become: yes

  - name: compile dwm
    make:
      chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
      target: install
    become: yes

  - name: compile dmenu
    make:
      chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dmenu"
      target: install
    become: yes
     
  - name: compile slock
    make:
      chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/slock"
      target: install
    become: yes

  - name: compile tabbed
    make:
      chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/tabbed"
      target: install
    become: yes

  # TODO: Make symlinks instead of copying

  - name: copy xinitrc
    ansible.builtin.copy:
      dest: "{{ ansible_user_dir }}/.xinitrc"
      src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.xinitrc"

  - name: copy xprofile
    ansible.builtin.copy:
      dest: "{{ ansible_user_dir }}/.xprofile"
      src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.xprofile"

  - name: copy Xresources
    ansible.builtin.copy:
      dest: "{{ ansible_user_dir }}/.Xresources"
      src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.Xresources"
