---
- hosts: localhost
  vars:
    fedora_current: 36

  tasks:
    - name: Set roles
      set_fact:
        roles: "{{ default_roles | difference(exclude_roles | default([])) }}"

    - name: Display roles
      debug: "var=roles"

    - name: Run roles
      include_role:
        name: '{{ roleinputvar }}'
      loop:
        - base
        - xorg
        - packages
      loop_control:
        loop_var: roleinputvar
        # name: base
        # name: xorg
        # - name: packages
      #   name: "{{ item }}"
      # with_items: "{{ roles }}"
