---
- hosts: localhost
  roles:
    - { role: base, tags: base }
    - { role: xorg, tags: xorg }
    - { role: packages, tags: packages }
    - { role: build, tags: build }
    - { role: custom, tags: custom }
