---
- hosts: localhost
  vars:
    fedora_current: 36

  tasks:
    - name: Set roles
      set_fact:
        roles: "{{ default_roles | difference(exclude_roles | default([])) }}"

    - name: Display roles
      debug: "var=roles"

    - name: Run roles
      include_role:
        - base
        - xorg
        - packages
      #   name: "{{ item }}"
      # with_items: "{{ roles }}"
