---
- hosts: localhost
  connection: local
  # roles:
  #   - xorg
  #   - suckless
  #   - general
  #
  tasks:
    - name: set roles
      set_fact:
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      debug: "var=roles"
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always

  # - name: install basic desktop
  #   package:
  #     name:
  #       - xorg-x11-server-Xorg
  #       - xorg-x11-xinit
  #       - libX11-devel
  #       - libXft-devel
  #       - libXinerama-devel
  #       - make
  #       - gcc
  #       - mesa-dri-drivers
  #       - xsetroot
  #     state: present
  #   become: yes

