---

- name: Install packages
  package:
    name:
      - hsetroot
      - firefox-esr
    state: present
  become: true

- name: Install neovim
  become: true
  ansible.builtin.apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb
