---
# - include_tasks: '{{ ansible_os_family }}.yml'

- name: Add the rpmfusion repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    # - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    # - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-36.noarch.rpm

- name: Install system packages
  package:
    name:
      - tar
      - wget
      - curl
      - xclip
      - xsetroot
      - fzf
      - unclutter-xfixes
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - neovim
      - zsh
      - kitty
      - alacritty
      - tmux
      - exa
      - ripgrep
      - ranger
      - ncdu
    state: present
  become: true

- name: Install applications
  package:
    name:
      - firefox
      - chromium
      - zathura
      - sxiv
      - mpv
    state: present
  become: true
