---
- include_tasks: '{{ ansible_os_family }}.yml'

- name: xorg utilities
  package:
    name:
      - xsetroot
      - xprop
      - xclip
      - xkill
    state: present
  become: true

- name: Install system packages
  package:
    name:
      - tar
      - wget
      - curl
      - arandr
      - fzf
      - unclutter-xfixes
      - picom
      - gtk3-devel
      - g++
      - sqlite
      - touchegg
      - touche
      - onboard
    state: present
  become: true

- name: pdf utilities
  package:
    name:
      - poppler-utils # -> pdfunite, pdfseparate
      - pdf-stapler
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - zsh
      - kitty
      - tmux
      - exa
      - ripgrep
      - ranger
      - ncdu
    state: present
  become: true

- name: Install applications
  package:
    name:
      - gimp
      - chromium
      - torbrowser-launcher
      - zathura
      - thunar
    state: present
  become: true

- name: Install graphical applications
  package:
    name:
      - gimp
      - inkscape
      - xournalpp
    state: present
  become: true

- name: Install browsers
  package:
    name:
      - chromium
      - torbrowser-launcher
    state: present
  become: true



