---
# - include_tasks: '{{ ansible_os_family }}.yml'

- name: install system packages
  package:
    name:
      - tar
      - wget
      - curl
      - xclip
      - xsetroot
      - fzf
      - unclutter-xfixes
    state: present
  become: true

- name: install cli tools
  package:
    name:
      - neovim
      - zsh
      - kitty
      - alacritty
      - tmux
      - exa
      - ripgrep
      - ranger
      - ncdu
    state: present
  become: true

- name: install applications
  package:
    name:
      - firefox
      - chromium
      - zathura
      - sxiv
      - mpv
    state: present
  become: true
