---
- include_tasks: '{{ ansible_os_family }}.yml'

- name: install system packages
  packgage:
    name:
      - tar
      - wget
      - curl
      - xclip
      - xsetroot
      - fzf
      - unclutter-xfixes
    state: present
    become: yes

- name: install cli tools
  packgage:
    name:
      - neovim
      - zsh
      - kitty
      - alacritty
      - tmux
      - exa
      - ripgrep
      - ranger
      - ncdu
    state: present
    become: yes

- name: install applications
  packgage:
    name:
      - firefox
      - chromium
      - zathura
      - sxiv
      - mpv
    state: present
    become: yes
