---
- include_tasks: '{{ ansible_os_family }}.yml'

# --
# pip
# --

- name: Install python packages (data science)
  pip:
    name:
      - jupyter-client
      - jupyterlab
      - jupyterlab-vim
      - pynvim
      - ipykernel
      - numpy
      - matplotlib
      - pandas
      - klepto # repl for sniprun
      # - tensorflow (not found)
    state: present

- name: Install python packages
  pip:
    name:
      - mkdocs
      - mkdocs-material
      - markdown-anki-decks
      - khal
      - vdirsyncer
      - khard
      - fahrplan
      - pulsemixer
      - trash-cli
    state: present

# --
# flatpak
# --

- name: add the flathub flatpak repository
  ansible.builtin.shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  community.general.flatpak:
    name:
      - io.typora.Typora
      - com.github.ahrm.sioyek

- name: link typora
  file:
    src: '/var/lib/flatpak/exports/bin/io.typora.Typora'
    dest: '$HOME/.local/bin/typora'
    state: link

- name: link typora
  file:
    src: '/var/lib/flatpak/exports/bin/com.github.ahrm.sioyek'
    dest: '$HOME/.local/bin/sioyek'
    state: link

# --
# cargo
# --

- name: install rust packages
  community.general.cargo:
    name: 
      - stylua
      - rbw
