---
- include_tasks: '{{ ansible_os_family }}.yml'

- name: Install system packages
  package:
    name:
      - tar
      - wget
      - curl
      - arandr
      - fzf
      - unclutter-xfixes
      - picom
      - gtk3-devel
      - g++
      - xsetroot
      - xprop
      - xclip
      - poppler-utils # pdfunite
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - zsh
      - kitty
      - tmux
      - exa
      - ripgrep
      - ranger
      - ncdu
    state: present
  become: true

- name: Install applications
  package:
    name:
      - chromium
      - zathura
      - sxiv
    state: present
  become: true
