---

- name: Install programming languages
  package:
    name:
      - nodejs
      - lua
      - rust
      - golang
      - python3-pip
      - cargo
    state: present
  become: true
    
- name: Install system packages
  package:
    name:
      - redshift
      - adwaita-qt5
      - qt5ct
      - xbacklight
      - acpi
      - tlp
      - picom
      - arandr
      - gnome-keyring
      - network-manager-applet
      - seahorse
      - nextcloud-client
      - autorandr
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - ncmpcpp
      - playerctl
      - mpdris2
      - texlive
      - newsboat
      - youtube-dl
      # - protonvpn-cli
    state: present
  become: true

- name: Install applications
  package:
    name:
      - qbittorrent
      - xournalpp
      - xsane
      - timeshift
      - anki
    state: present
  become: true

- name: install protonvpn rpm from a remote repo
  dnf:
    name: 'https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm'
    state: present

# TODO: Add rpmfusion repos

# - name: Install non free packages
#   package:
#     name:
#       - mpv
#       - mpd
#     state: present
#   become: true
