---

# Typora
- name: Check if typora installed
  shell: command -v cat >/dev/null 2>&1
  register: typora_installed
  ignore_errors: true 

- debug: msg="{{ typora_installed }}
#
# - name: download typora
#   ansible.builtin.get_url:
#     url: https://download.typora.io/linux/Typora-linux-x64.tar.gz
#     dest: "{{ ansible_user_dir }}/.local/share/typora"
#   when: typora


- name: add the rpmfusion repo packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-36.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-36.noarch.rpm

# Install packages

- name: Install programming languages
  package:
    name:
      - nodejs
      - lua
      - rust
      - golang
      - python3-pip
      - cargo
    state: present
  become: true
    
- name: Install system packages
  package:
    name:
      - redshift
      - adwaita-qt5
      - qt5ct
      - xbacklight
      - acpi
      - tlp
      - picom
      - arandr
      - gnome-keyring
      - network-manager-applet
      - seahorse
      - nextcloud-client
      - autorandr
      - gtk3
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - ncmpcpp
      - playerctl
      - mpdris2
      - texlive
      - newsboat
      - youtube-dl
    state: present
  become: true

- name: Install applications
  package:
    name:
      - qbittorrent
      - xournalpp
      - xsane
      - timeshift
      - anki
      - mpv
      - mpd
    state: present
  become: true

# RPM Remote Repositories

- name: Install protonvpn
  become: true
  dnf:
    name: 'https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm'
    disable_gpg_check: yes
    state: present

- name: Install masterpdfeditor
  become: true
  dnf:
    name: 'https://code-industry.net/public/master-pdf-editor-5.8.46-qt5.x86_64.rpm'
    disable_gpg_check: yes
    state: present

- name: Install onlyoffice
  become: true
  dnf:
    name: 'https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm'
    disable_gpg_check: yes
    state: present

- name: Install gotop
  become: true
  dnf:
    name: 'https://github.com/xxxserxxx/gotop/releases/download/v4.1.3/gotop_v4.1.3_linux_amd64.rpm'
    disable_gpg_check: yes
    state: present

# Git Repositories
- name: clone dmenu networkmanager
  git:
    repo: https://github.com/firecat53/networkmanager-dmenu.git
    dest: "{{ ansible_user_dir }}/.local/bin/networkmanager-dmenu"
    update: no
- name: clone todotxt
  git:
    repo: https://github.com/todotxt/todo.txt-cli.git
    dest: "{{ ansible_user_dir }}/.local/share/todotxt"
    update: no

- name: compile todotxt
  make:
    chdir: "{{ ansible_user_dir }}/.local/share/todotxt"
    target: install
  become: true

- name: clone dragon
  git:
    repo: https://github.com/mwh/dragon.git
    dest: "{{ ansible_user_dir }}/.local/share/dragon"
    update: no

- name: compile dragon
  make:
    chdir: "{{ ansible_user_dir }}/.local/share/dragon"
    target: install
  become: true

- name: clone devour
  git:
    repo: https://github.com/salman-abedin/devour.git    
    dest: "{{ ansible_user_dir }}/.local/share/devour"
    update: no

- name: compile devour
  make:
    chdir: "{{ ansible_user_dir }}/.local/share/devour"
    target: install
  become: true

