---

- name: add the rpmfusion repo packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest


- name: install latex packages
  become: true
  package:
    name:
      - latexmk

- name: install programming languages
  become: true
  package:
    name:
      - nodejs
      - lua
      - rust
      - golang
      - python3-pip
      - conda
      - cargo
      - java-17-openjdk

    state: present

- name: install applets
  become: true
  package:
    name:
      - network-manager-applet
      - blueberry
      - pasystray
    state: present

- name: Install system packages
  package:
    name:
      - neovim
      - redshift
      - xbacklight
      - brightnessctl
      - acpi
      - tlp
      - alacritty
      - gnome-keyring
      - libevdev-devel # needed for evdev-rightclick
      - gnome-keyring-pam
      - seahorse
      - nextcloud-client
      - autorandr
      - gtk3
      - dunst
      - xsel
      - xset
      - trash-cli
      - autojump-zsh
      - pandoc
      - mediawriter
      - imlib2-devel # needed for hsetroot
    state: present
  become: true

- name: install cli tools
  package:
    name:
      - texlive
      - newsboat
      - youtube-dl
    state: present
  become: true

- name: multimedia package
  package:
    name:
      - mpv
      - mpd
      - mpc
      - mpdris2
      - ncmpcpp
      - playerctl
      - xbindkeys
    state: present
  become: true

- name: install applications
  package:
    name:
      - lpf-spotify-client
      - qbittorrent
      - pavucontrol
      - okular
      - xsane
      - timeshift
      - flameshot
      - qutebrowser
      - rofi
      - openvpn  
      - NetworkManager-openvpn 
      - NetworkManager-openvpn-gnome
    state: present
  become: true

- name: install virtualization packages
  package:
    name:
      - bridge-utils
      - libvirt
      - virt-install
      - qemu
      - qemu-kvm
      - VirtualBox
      - virtualbox-guest-additions
  become: true

- name: install firefox
  dnf:
    name: firefox
    disable_gpg_check: yes
  become: true

# ---
# rawhide repos (dev branch)
# ---

- name: enable rawhide repos
  package:
    name:
      - fedora-repos-rawhide
  become: true

- name: install rawhide packages
  package:
    name:
      - neovim
    enablerepo: rawhide
  become: true
