---

- name: add the rpmfusion repo packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-36.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-36.noarch.rpm

- name: Install programming languages
  package:
    name:
      - nodejs
      - lua
      - rust
      - golang
      - python3-pip
      - cargo
    state: present
  become: true
    
- name: Install system packages
  package:
    name:
      - redshift
      - adwaita-qt5
      - qt5ct
      - xbacklight
      - acpi
      - tlp
      - picom
      - arandr
      - gnome-keyring
      - network-manager-applet
      - seahorse
      - nextcloud-client
      - autorandr
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - ncmpcpp
      - playerctl
      - mpdris2
      - texlive
      - newsboat
      - youtube-dl
    state: present
  become: true

- name: Install applications
  package:
    name:
      - qbittorrent
      - xournalpp
      - xsane
      - timeshift
      - anki
      - mpv
      - mpd
    state: present
  become: true


- name: install protonvpn rpm from a remote repo
  become: true
  dnf:
    name: 'https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm'
    disable_gpg_check: yes
    state: present

- name: install masterpdfeditor rpm from a remote repo
  become: true
  dnf:
    name: 'https://code-industry.net/public/master-pdf-editor-5.8.46-qt5.x86_64.rpm'
    disable_gpg_check: yes
    state: present

- name: install onlyoffice rpm from a remote repo
  become: true
  dnf:
    name: 'https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm'
    disable_gpg_check: yes
    state: present
