---

- name: Install programming languages
  package:
    name:
      - nodejs
      - lua
      - rust
      - golang
      - python3-pip
      - cargo
    state: present
  become: true
    
- name: Install system packages
  package:
    name:
      - redshift
      - adwaita-qt5
      - qt5ct
      - xbacklight
      - acpi
      - tlp
      - picom
      - arandr
      - gnome-keyring
      - network-manager-applet
      - seahorse
      - nextcloud-client
    state: present
  become: true

- name: Install cli tools
  package:
    name:
      - ncmpcpp
      - playerctl
      - mpdris2
      - texlive
      - newsboat
    state: present
  become: true

- name: Install applications
  package:
    name:
      - qbittorrent
      - xournalpp
      - xsane
      - timeshift
      - anki
    state: present
  become: true

- name: Install non free packages
  package:
    name:
      - mpv
      - mpd
    state: present
  become: true
