#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import Current Theme
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/styles/text.rasi"

# Layout
list_col='1'
list_row='5'

# Options
option_1="	Back"
option_2="	Files"
option_3="	Browser"
option_4="	Terminal"
option_5="	Spotify"

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'window {location: center; anchor: center; fullscreen: false; width: 500px;}' \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		sleep 0.2
		$ROFI_DIR/launcher
        ;;
    $option_2)
		thunar
        ;;
    $option_3)
		qutebrowser
        ;;
    $option_4)
		kitty
        ;;
    $option_5)
		spotify --force-device-scale-factor=1.5
        ;;
esac

