#!/usr/bin/env bash

# Import Current Theme
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/styles/icon.rasi"

list_col='6'
list_row='1'

option_1="爵"
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-dmenu \
		-markup-rows \
		-steal-focus \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		$ROFI_DIR/quicklinks
        ;;
    $option_2)
		$ROFI_DIR/powermenu
        ;;
    $option_3)
		$ROFI_DIR/apps
        ;;
    $option_4)
		blueberry
        ;;
    $option_5)
		$ROFI_DIR/settings
        ;;
esac

