#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import Current Theme
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/shared/style-1.rasi"

list_col='6'
list_row='1'

option_1="爵"
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-dmenu \
		-markup-rows \
		-steal-focus \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}


# Execute Command
run_cmd() {
	sleep 0.2 # Smoother Transition
	if [[ "$1" == '--opt1' ]]; then
		$ROFI_DIR/quicklinks
	elif [[ "$1" == '--opt2' ]]; then
		$ROFI_DIR/powermenu
	elif [[ "$1" == '--opt3' ]]; then
		$ROFI_DIR/apps
	elif [[ "$1" == '--opt4' ]]; then
		blueberry
	elif [[ "$1" == '--opt5' ]]; then
		$ROFI_DIR/settings
	elif [[ "$1" == '--opt6' ]]; then
		dunstify "option 6"
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac

