#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Quick Links

# Import Current Theme
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/styles/text.rasi"

# Theme Elements
prompt='Quick Links'

list_col='2'
list_row='4'

option_1="	Back"
option_2="	SBB"
option_3="	Kindle"
option_4="	Youtube"
option_5="	Maps"
option_6="	Mail"
option_7="	Teams"
option_8="	Calendar"

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'window {location: center; anchor: center; fullscreen: false; width: 800px;}' \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-theme-str "element-text {font: \"$efonts\";}" \
		-dmenu \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6\n$option_7\n$option_8" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		sleep 0.2
		$ROFI_DIR/launcher
        ;;
    $option_2)
		xdg-open 'https://www.sbb.ch/'
        ;;
    $option_3)
		xdg-open 'https://read.amazon.com/kindle-library'
        ;;
    $option_4)
		xdg-open 'https://www.yewtu.be/'
        ;;
    $option_5)
		xdg-open 'https://www.google.com/maps'
        ;;
    $option_6)
		xdg-open 'https://mail.proton.me'
        ;;
    $option_7)
		xdg-open 'https://teams.microsoft.com/'
        ;;
    $option_8)
		xdg-open 'https://220624z6bmfrl5nztze.nextcloud.hosting.zone/apps/calendar/timeGridWeek/now'
        ;;
	*)
		exit
		;;
esac
