#!/bin/bash

DIRS="lectures out --sync --delete"
ARGS="--sync --delete --prefix"
HOMEDIR="/home/fabian/nextcloud/mcs/"

select subject in asse hci cyber 
do 
	cd $HOMEDIR/docs/$subject/
	mdankideck $DIRS $ARGS \"$subject::\"
	exit
done
