#!/usr/bin/env bash

# create server if not already running
if ! tmux has-session -t="docs" 2> /dev/null; then
    tmux new-session -ds "docs"
	tmux new-window -n mkdocs  -t docs
	tmux send-keys -t docs:mkdocs "cd $HOME/nextcloud/mcs/ && mkdocs serve" ENTER
	tmux send-keys -t docs:zsh "cd ~/nextcloud/mcs/ && nvim docs/index.md" Enter
fi

# select dir
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/nextcloud/mcs/core  ~/nextcloud/mcs/electives ~/nextcloud/mcs/context -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# exit if no selection
if [[ -z $selected ]]; then
    exit 0
fi

# sanitize name
selected_name=$(basename "$selected" | tr . _)

# create selected session
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
	tmux neww -dn notes -t $selected_name
fi

# open notes
tmux send-keys -t $selected_name:notes "cd $HOME/nextcloud/mcs/docs/$selected_name && nvim ." Enter


tmux switch-client -t $selected_name
