---
- name: link xinitrc
  file:
    src: "$HOME/.dotfiles/config/xorg/.xinitrc"
    dest: "$HOME/.xinitrc"
    state: link

- name: link xprofile
  file:
    src: "$HOME/.dotfiles/config/xorg/.xprofile"
    dest: "$HOME/.xprofile"
    state: link

- name: link Xresources
  file:
    src: "$HOME/.dotfiles/config/xorg/.Xresources"
    dest: "$HOME/.Xresources"
    state: link

- name: link Xmodmap
  file:
    src: "$HOME/.dotfiles/config/xorg/.Xmodmap"
    dest: "$HOME/.Xmodmap"
    state: link

