---
- name: link xinitrc
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/roles/xorg/files/.xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    state: link

- name: link xprofile
  file:
    src: ".xprofile"
    dest: "{{ ansible_user_dir }}/.xprofile"
    state: link

- name: link Xresources
  file:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    state: link
