---
- name: link xinitrc
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    state: link

- name: link xprofile
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.xprofile"
    dest: "{{ ansible_user_dir }}/.xprofile"
    state: link

- name: link Xresources
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/config/xorg/.Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    state: link
