---

- include_tasks: '{{ ansible_os_family }}.yml'

- name: clone neovim
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    update: no

- name: link tmuxdd
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/scripts/utils/tmuxdd"
    dest: "{{ ansible_user_dir }}/.local/bin/tmuxdd"
    state: link

- name: link statusinfo
  become: true
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/scripts/utils/statusinfo"
    dest: "/usr/bin/statusinfo"
    state: link

- name: gtk file chooser window size
  ansible.builtin.shell:
    cmd: gsettings set org.gtk.Settings.FileChooser window-size '(1200, 800)'

- name: install gotop
  ansible.builtin.shell:
    cmd: go install github.com/xxxserxxx/gotop/v4/cmd/gotop@latest

- name: install spicetify
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh


