---

- include_tasks: '{{ ansible_os_family }}.yml'

- name: clone neovim
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    update: no
