---

- name: Install automatic updates
  package:
    name: dnf-automatic
    state: present
  become: true

- name: Enable automatic updates
  become: true
  systemd:
    name: tlp
    enabled: yes

- name: clone neovim
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    update: no
