- include_tasks: "{{ ansible_os_family }}.yml"

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: install dwm
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
    target: install
  become: yes

- name: install dmenu
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dmenu"
    target: install
  become: yes
    
- name: install slock
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/slock"
    target: install
  become: yes

- name: install tabbed
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/tabbed"
    target: install
  become: yes
