#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu, emacsclient
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson
#               HostGrady
# Usage:
# to use other editor than emacsclient set DMEDITOR accordingly
#   Example: `DMEDITOR="alacritty -e nvim" ./dmconf`
DMCONFIG="$HOME/.config/dmscripts/dmconf"
if [ -f "$DMCONFIG" ]; then
	source "$DMCONFIG"
else
	: "${DMEDITOR:=alacritty -e tmux new-window lvim}"
# An array of options to choose.
# You can edit this list to add/remove config files.
	declare -A options
        options[alacritty]="$HOME/.dotfiles/alacritty/alacritty.yml"
        options[alias]="$HOME/.dotfiles/zsh/zsh-aliases"
        options[dmconf]="$HOME/.dotfiles/scripts/dmenu/dmconf"
        options[dmenu]="$HOME/.dotfiles/dmenu/config.def.h"
        options[dmlogout]="$HOME/.dotfiles/scripts/dmenu/dmlogout"
        options[dotbot]="$HOME/.dotfiles/install.conf.yaml"
        options[dunst]="$HOME/.dotfiles/dunst/dunstrc"
        options[dwm]="$HOME/.dotfiles/dwm/config.def.h"
        options[userChrome]="$HOME/.dotfiles/firefox/userChrome.css"
        options[install.sh]="$HOME/.dotfiles/scripts/installer/install.sh"
        options[neovim]="$HOME/.dotfiles/nvim/config.lua"
        options[ranger config]="$HOME/.dotfiles/ranger/rc.conf"
        options[ranger pager]="$HOME/.dotfiles/ranger/rifle.conf"
        options[tridactyl]="/$HOME/.config/tridactyl/tridactylrc"
        options[typora]="$HOME/.dotfiles/typora/conf.user.json"
        options[xprofile]="$HOME/.xprofile"
        options[xresources]="$HOME/.Xresources"
        options[zshrc]="$HOME/.dotfiles/zsh/.zshrc"
        options[scimrc]="$HOME/.dotfiles/sc-im/scimrc"
        options[scimrc help]="$HOME/.config/sc-im/help"
        options[newsboat urls]="$HOME/.dotfiles/newsboat/urls"
        options[newsboat config]="$HOME/.dotfiles/newsboat/config"
        options[mpv input]="$HOME/.dotfiles/misc/mpv/input.conf"


fi
# Clean options array making sure that the files exist
declare -A options_clean
  for i in "${!options[@]}"; do
    [[ -f ${options["${i}"]} ]] && options_clean["${i}"]=${options["${i}"]}
  done

# Piping the above array (cleaned) into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${!options_clean[@]}" | sort | dmenu -l 30 -i -p  'Edit config:' "$@" )

# What to do when/if we choose a file to edit.
if [ "$choice" ]; then
  cfg=$(printf '%s\n' "${options_clean["${choice}"]}")
  $DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
