- defaults:
    link:
      create: true    # Create parent directories as needed
      force: true     # Removes the old target and forces a new link

- clean: ['~']

- link:
    ~/.config/autorandr:                    autorandr
    ~/.config/mutt:                         mail/mutt
    ~/.mbsyncrc:                            mail/.mbsyncrc
    ~/.config/touchegg:                     touchegg
    ~/.config/qutebrowser:                  qutebrowser
    ~/.local/share/fonts:                   fonts
    ~/.config/yt-dlp:                       yt-dlp
    ~/.tmux.conf:                           tmux/tmux.conf
    ~/.config/rofi/themes:                  rofi/themes
    ~/.config/rofi/config.rasi:             rofi/config.rasi
    ~/.config/khal:                         khal  
    ~/.config/khard:                        khard  
    ~/.config/vdirsyncer:                   vdirsyncer
    ~/.newsboat:                            newsboat
    ~/.config/mpv:                          mpv
    ~/.xbindkeysrc:                         xorg/.xbindkeysrc
    ~/.xinitrc:                             xorg/.xinitrc
    ~/.xprofile:                            xorg/.xprofile
    ~/.config/spicetify/Extensions/keyboardShortcut.js: spicetify/keyboardShortcut.js
    ~/.config/spicetify/config-xpui.ini:    spicetify/config-xpui.ini
    ~/.config/lf:                           lf
    ~/.config/xournalpp:                    xournal
    ~/.config/dunst:                        dunst
    ~/.config/sioyek:                       sioyek
