- defaults:
    link:
      create: true    # Create parent directories as needed
      force: true     # Removes the old target and forces a new link

- clean: ['~']

- link:
    ~/.config/sxiv:                         sxiv
    ~/.config/qutebrowser:                  qutebrowser
    ~/.config/zsh:                          zsh
    ~/.config/rbw:                          rbw
    ~/.local/share/fonts:                   fonts
    ~/.config/keyboard.conf:                setxkbmap/keyboard.conf
    ~/.tmux.conf:                           tmux/tmux.conf
    ~/.config/rofi:                         rofi
    ~/.latexmkrc:                           latex/.latexmkrc
    ~/.config/khal:                         khal  
    ~/.config/khard:                        khard  
    ~/.config/alacritty:                    alacritty
    ~/.config/kitty:                        kitty
    ~/.newsboat:                            newsboat
    ~/.config/Typora/conf/conf.user.json:   typora/conf.user.json
    ~/.config/Typora/themes/nord:           typora/nord
    ~/.config/Typora/themes/nord.css:       typora/nord.css
    ~/.config/gtk-3.0/settings.ini:         gtk/settings.ini
    ~/.gtkrc-2.0:                           gtk/.gtkrc-2.0
    ~/.config/qt5ct/qt5ct.conf:             qt/qt5ct.conf
    ~/.config/qt6ct/qt6ct.conf:             qt/qt6ct.conf
    ~/.config/qt5ct/colors/nord.conf:       qt/nord.conf 
    ~/.config/qt6ct/colors/nord.conf:       qt/nord.conf 
    ~/.themes/Nordic:                       gtk/Nordic
    ~/.config/redshift:                     redshift
    ~/.config/mpv:                          mpv
    ~/.config/mpd:                          mpd
    ~/.xbindkeysrc:                         xutils/.xbindkeysrc
    ~/.config/mimeapps.list:                xutils/mimeapps.list
    ~/.config/mpDris2:                      mpDris2
    ~/.ncmpcpp:                             ncmpcpp
    ~/.spicetify/Extensions/keyboardShortcut.js: spicetify/keyboardShortcut.js
    ~/.config/spicetify/config-xpui.ini:    spicetify/config-xpui.ini
    ~/.config/ranger/rc.conf:               ranger/rc.conf
    ~/.config/ranger/rifle.conf:            ranger/rifle.conf
    ~/.config/ranger/plugins:               ranger/plugins
    ~/.config/qBittorrent/qBittorrent.conf: qBittorrent/qBittorrent.conf
    ~/.config/zathura:                      zathura
    ~/.config/xournalpp:                    xournal
    ~/.config/tridactyl/tridactylrc:        firefox/tridactylrc.vim
    ~/.config/tridactyl/themes/nord.css:    firefox/nord.css
    ~/.config/dunst:                        dunst
    ~/.local/share/flatpak/app/com.github.ahrm.sioyek/x86_64/stable/active/files/sioyek/keys_user.config: sioyek/keys_user.config
    ~/.local/share/flatpak/app/com.github.ahrm.sioyek/x86_64/stable/active/files/sioyek/prefs_user.config: sioyek/prefs_user.config
