- defaults:
    link:
      create: true    # Create parent directories as needed
      force: true     # Removes the old target and forces a new link

- clean: ['~']

- link:

    # SYSTEM ------------------------------------------------------
    ~/.config/zsh:                          zsh
    ~/.local/share/fonts:                   fonts
    ~/.config/keyboard.conf:                setxkbmap/keyboard.conf
    ~/.tmux.conf:                           tmux/tmux.conf
    ~/.local/bin/tmuxdd:                    tmux/tmuxdd

    # UTILITIES ---------------------------------------------------
    ~/.latexmkrc:                           latex/.latexmkrc
    ~/.mutt/muttrc:                         neomutt/muttrc
    ~/.config/khal:                         khal  
    ~/.config/alacritty:                    alacritty
    ~/.config/kitty:                        kitty
    ~/.newsboat:                            newsboat
    ~/.config/Typora/conf/conf.user.json:   typora/conf.user.json
    ~/.config/Typora/themes/nord:           typora/nord
    ~/.config/Typora/themes/nord.css:       typora/nord.css
    ~/.config/gtk-3.0/settings.ini:         gtk/settings.ini
    ~/.gtkrc-2.0:                           gtk/.gtkrc-2.0
    ~/.config/qt5ct/qt5ct.conf:             qt/qt5ct.conf
    ~/.config/qt6ct/qt6ct.conf:             qt/qt6ct.conf
    ~/.config/qt5ct/colors/nord.conf:       qt/nord.conf 
    ~/.config/qt6ct/colors/nord.conf:       qt/nord.conf 
    ~/.themes/Nordic:                       gtk/Nordic
    ~/.config/redshift:                     redshift
    ~/.config/mpv:                          mpv
    ~/.config/mpd:                          mpd
    ~/.xbindkeysrc:                         xutils/.xbindkeysrc
    ~/.config/mimeapps.list:                xutils/mimeapps.list
    ~/.config/mpDris2:                      mpDris2
    ~/.ncmpcpp:                             ncmpcpp
    # ~/.local/bin/rumno:                     rumno/build/target/release/rumno
    # ~/.local/bin/rumno-background:          rumno/build/target/release/rumno-background
    #
    # SIOYEK
    ~/.local/share/flatpak/app/com.github.ahrm.sioyek/x86_64/stable/active/files/sioyek/keys_user.config: sioyek/keys_user.config
    ~/.local/share/flatpak/app/com.github.ahrm.sioyek/x86_64/stable/active/files/sioyek/prefs_user.config: sioyek/prefs_user.config


    # TOOLS -------------------------------------------------------
    ~/.spicetify/Extensions/keyboardShortcut.js: spicetify/keyboardShortcut.js
    ~/.config/spicetify/config-xpui.ini:    spicetify/config-xpui.ini
    ~/.config/ranger/rc.conf:               ranger/rc.conf
    ~/.config/ranger/rifle.conf:            ranger/rifle.conf
    ~/.config/ranger/plugins:               ranger/plugins
    ~/.config/qBittorrent/qBittorrent.conf: qBittorrent/qBittorrent.conf
    ~/.config/zathura:                      zathura
    ~/.config/xournalpp:                    xournal

    # WEB TOOLS ---------------------------------------------------
    ~/.config/tridactyl/tridactylrc:        firefox/tridactylrc.vim
    ~/.config/tridactyl/themes/nord.css:    firefox/nord.css


    # ARCHIVED ----------------------------------------------------
    # ~/.config/rofi/config:                  .archive/rofi/config
    # ~/.config/rofi/themes/minimal.rasi:     .archive/rofi/minimal.rasi
    # ~/.config/autorandr/postswitch:         .archive/autorandr/postswitch
    ~/.config/dunst:                        dunst
