

# ---
# rpm remote packages
# ---

- name: install protonvpn
  become: true
  dnf:
    name: 'https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm'
    disable_gpg_check: yes
    state: present

- name: install masterpdfeditor
  become: true
  dnf:
    name: 'https://code-industry.net/public/master-pdf-editor-5.8.46-qt5.x86_64.rpm'
    disable_gpg_check: yes
    state: present

# - name: install onlyoffice
#   become: true
#   dnf:
#     name: 'https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm'
#     disable_gpg_check: yes
#     state: present

# - name: install zoom
#   become: true
#   dnf:
#     name: 'https://zoom.us/client/latest/zoom_x86_64.rpm'
#     disable_gpg_check: yes
#     state: present

# --
# copr
# --

- name: enable blanket
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: tuxino/Blob
  become: true

- name: enable lazygit
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: atim/lazygit
  become: true

- name: enable neomutt
  community.general.copr:
    host: copr.fedorainfracloud.org
    name:  flatcap/neomutt
  become: true

- name: enable font-manager
  community.general.copr:
    host: copr.fedorainfracloud.org
    name:  jerrycasiano/FontManager
  become: true

- name: install packages
  package:
    name:
      - blanket
      - lazygit
      - neomutt
    state: present
  become: true

# --
# neomutt
# --

- name: mail with mutt
  package:
    name:
      - isync     # sync mail to local storage
      - lynx      # display html
      - notmuch   # search mail
      - msmtp     # send mail
  become: true

- name: create mail directory if it does not exist
  ansible.builtin.file:
    path: $HOME/.mail
    state: directory
    mode: '0755'

# --
# pip
# --

- name: Install python packages (data science)
  pip:
    name:
      - pynvim
      - jupyter-client
      - ueberzug
      - ipykernel
      - tensorflow
      - numpy
      - matplotlib
    state: present

- name: Install python packages
  pip:
    name:
      - mkdocs
      - mkdocs-material
      - markdown-anki-decks
      - khal
      - vdirsyncer
      - khard
      - fahrplan
      - pulsemixer
      - trash-cli
      - tldextract # bitwarden login script
    state: present

# Spotifyd Steps
# 1. Clone Repo
# 2. cargo --build release (requires dnf install alsa-lib-devel)
# 3. cargo install --path . --locked (installs binary)
# 4. Run it as sytemd service (https://spotifyd.github.io/spotifyd/config/services/Systemd.html#running-spotifyd-as-a-systemd-service)
# Note: Important that binary in /usr/bin/spotifyd

# --
# flatpak
# --

- name: add the flathub flatpak repository
  ansible.builtin.shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  community.general.flatpak:
    name:
      - org.signal.Signal
      - io.typora.Typora
      - com.spotify.Client
      - com.obsproject.Studio
      - com.github.ahrm.sioyek

- name: link typora
  file:
    src: '/var/lib/flatpak/exports/bin/io.typora.Typora'
    dest: '$HOME/.local/bin/typora'
    state: link

- name: link signal
  file:
    src: '/var/lib/flatpak/exports/bin/org.signal.Signal'
    dest: '$HOME/.local/bin/signal'
    state: link

- name: link spotify
  file:
    src: '/var/lib/flatpak/exports/bin/com.spotify.Client'
    dest: '$HOME/.local/bin/spotify'
    state: link

- name: link obs
  file:
    src: '/var/lib/flatpak/exports/bin/com.obsproject.Studio'
    dest: '$HOME/.local/bin/obs'
    state: link

# --
# cargo
# --

- name: install rust packages
  community.general.cargo:
    name: 
      - stylua
      - rbw
