# ---
# rpm remote packages
# ---

- name: install protonvpn
  become: true
  dnf:
    name: 'https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm'
    disable_gpg_check: yes
    state: present

- name: install masterpdfeditor
  become: true
  dnf:
    name: 'https://code-industry.net/public/master-pdf-editor-5.8.46-qt5.x86_64.rpm'
    disable_gpg_check: yes
    state: present

# - name: install onlyoffice
#   become: true
#   dnf:
#     name: 'https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm'
#     disable_gpg_check: yes
#     state: present

# - name: install zoom
#   become: true
#   dnf:
#     name: 'https://zoom.us/client/latest/zoom_x86_64.rpm'
#     disable_gpg_check: yes
#     state: present

# --
# copr
# --

- name: enable blanket
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: tuxino/Blob
  become: true

- name: enable lazygit
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: atim/lazygit
  become: true

- name: install packages
  package:
    name:
      - blanket
      - lazygit
    state: present
  become: true
# --
# pip
# --

# - name: Install python packages (data science)
#   pip:
#     name:
#       - pynvim
#       - jupyter-client
#       - jupyterlab-autosave-on-focus-change
#       - ueberzug
#       - ipykernel
#       - tensorflow
#       - numpy
#       - matplotlib
#     state: present

- name: install python packages
  pip:
    name:
      - mkdocs
      - mkdocs-material
      - markdown-anki-decks
      - khal
      - vdirsyncer
      - khard
      - fahrplan
      - pulsemixer
      - trash-cli
    state: present

- name: install rust packages
  community.general.cargo:
    name:
      - rbw

# Spotifyd Steps
# 1. Clone Repo
# 2. cargo --build release (requires dnf install alsa-lib-devel)
# 3. cargo install --path . --locked (installs binary)
# 4. Run it as sytemd service (https://spotifyd.github.io/spotifyd/config/services/Systemd.html#running-spotifyd-as-a-systemd-service)
# Note: Important that binary in /usr/bin/spotifyd

# --
# flatpak
# --

- name: add the flathub flatpak repository
  ansible.builtin.shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  community.general.flatpak:
    name:
      - org.signal.Signal
      - io.typora.Typora
      - com.spotify.Client
      - com.obsproject.Studio
    method: user

- name: link typora
  file:
    src: '$HOME/.local/share/flatpak/exports/bin/io.typora.Typora'
    dest: '$HOME/.local/bin/typora'
    state: link

- name: link signal
  file:
    src: '$HOME/.local/share/flatpak/exports/bin/org.signal.Signal'
    dest: '$HOME/.local/bin/signal'
    state: link

- name: link spotify
  file:
    src: '$HOME/.local/share/flatpak/exports/bin/com.spotify.Client'
    dest: '$HOME/.local/bin/spotify'
    state: link

- name: link obs
  file:
    src: '$HOME/.local/share/flatpak/exports/bin/com.obsproject.Studio'
    dest: '$HOME/.local/bin/obs'
    state: link

# --
# cargo
# --

- name: install rust packages
  community.general.cargo:
    name: stylua
