---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: install suckless dependencies
  package:
    name:
      - xorg
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
    state: present
  become: yes

- name: install dwm
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
    target: install
  become: yes
