---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: compile dwm
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
    target: install
  become: yes

- name: compile dmenu
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dmenu"
    target: install
  become: yes
   
- name: compile slock
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/slock"
    target: install
  become: yes

- name: compile tabbed
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/tabbed"
    target: install
  become: yes

- name: link xinitrc
  file:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/.xinitrc"
    state: link

- name: link xprofile
  file:
    src: ".xprofile"
    dest: "{{ ansible_user_dir }}/.xprofile"
    state: link

- name: link Xresources
  file:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
    state: link
