---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: build dwm
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
  become: true

- name: compile dwm
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dwm"
    target: install
  become: true

- name: build dmenu
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dmenu"
  become: true

- name: compile dmenu
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/dmenu"
    target: install
  become: true

- name: build slock
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/slock"
  become: true
   
- name: compile slock
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/slock"
    target: install
  become: true

- name: build slock
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/tabbed"
  become: true

- name: compile tabbed
  make:
    chdir: "{{ ansible_user_dir }}/.dotfiles/config/suckless/tabbed"
    target: install
  become: true
