---
- name: install basic desktop
  package:
    name:
      - xorg-x11-server-Xorg
      - xorg-x11-xinit
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - dbus-x11
      - make
      - gcc
      - mesa-dri-drivers
    state: present
  become: true
