---

- include_tasks: '{{ ansible_os_family }}.yml'

- name: clone neovim
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "$HOME/.config/nvim"
    update: no

- name: gtk file chooser window size
  ansible.builtin.shell:
    cmd: gsettings set org.gtk.Settings.FileChooser window-size '(1200, 800)'

- name: idle screen timeout delay
  ansible.builtin.shell:
    cmd: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout -1

- name: install gotop
  ansible.builtin.shell:
    cmd: go install github.com/xxxserxxx/gotop/v4/cmd/gotop@latest

- name: install spicetify
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

- name: install sioyek
  ansible.builtin.shell: 
    cmd: $HOME/.dotfiles/roles/misc/files/get-sioyek.sh

# Spicetify permissions
- name: read/write permissions for spicetify
  ansible.builtin.file:
    path: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
    state: directory
    mode: 'a+wr'
  become: true

- name: read/write permissions for spicetify
  ansible.builtin.file:
    path: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
    state: directory
    mode: 'a+wr'
  become: true

# Cron environment
- name: Add "SHELL" environment variable to crontab
  ansible.builtin.cron:
    name: SHELL
    env: yes
    job: /bin/zsh

- name: Add "MAILTO" environment variable to crontab
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: $MAIL_ADDRESS

# Cronjobs
- name: cron entry - check mail 
  ansible.builtin.cron:
    name: "sync mailbox (every 5 minutes)"
    minute: "*/5"
    job: "killall mbsync &>/dev/null; mbsync protonmail" 

- name: cron entry - backup vm 
  ansible.builtin.cron:
    name: "backup virtual machine (every week)"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "VBoxManage export 'Win10' -o '$HOME/nextcloud/apps/vms/Win10/(date +'%Y-%m-%d')-Win10.ova'"

- name: cron entry - update blacklist 
  ansible.builtin.cron:
    name: "sync blacklist (every week)"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "$HOME/.dotfiles/scripts/utils/blacklist"

- name: cron entry - trash downloaded files 
  ansible.builtin.cron:
    name: "trash downloads (at 5 AM)"
    hour: "5"
    minute: "0"
    job: "trash $HOME/Downloads/*"

- name: cron entry - push dotfiles 
  ansible.builtin.cron:
    name: "push dotfiles (at 5 AM)"
    hour: "5"
    minute: "0"
    job: "cd $HOME/.dotfiles && git add . && git commit -m 'automated update' && git push origin main"

- name: cron entry - push neovim config 
  ansible.builtin.cron:
    name: "push neovim (at 5 AM)"
    hour: "5"
    minute: "0"
    job: "cd $HOME/.config/nvim && git add . && git commit -m 'automated update' && git push origin main"

- name: cron entry - delete trashed items 
  ansible.builtin.cron:
    name: "empty trash older than 30 days (every week)"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "trash-empty 30"

