---

- include_tasks: '{{ ansible_os_family }}.yml'

- name: clone neovim configuration
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "$HOME/.config/nvim"
    update: no

- name: gtk file chooser window size
  ansible.builtin.shell:
    cmd: gsettings set org.gtk.Settings.FileChooser window-size '(1200, 800)'

# -- 
# setup cron
# --

# environment
- name: Add "SHELL" environment variable to crontab
  ansible.builtin.cron:
    name: SHELL
    env: yes
    job: /bin/zsh

- name: Add "MAILTO" environment variable to crontab
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: $MAIL_ADDRESS

# cron entries
- name: cron entry - check mail 
  ansible.builtin.cron:
    name: "sync mailbox (every 5 minutes)"
    minute: "*/5"
    job: "killall mbsync &>/dev/null; mbsync protonmail" 

- name: cron entry - backup vm 
  ansible.builtin.cron:
    name: "backup virtual machine (every week)"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "VBoxManage export 'Win10' -o '$HOME/nextcloud/apps/vms/Win10/(date +'%Y-%m-%d')-Win10.ova'"

- name: cron - update blacklist 
  ansible.builtin.cron:
    name: "sync blacklist (every week)"
    weekday: "0"
    minute: "0"
    hour: "11"
    job: "$HOME/.dotfiles/scripts/cron/update-blacklist"

- name: cron - trash downloaded files 
  ansible.builtin.cron:
    name: "trash downloads (at 11 AM)"
    hour: "11"
    minute: "0"
    job: "trash $HOME/Downloads/*"

- name: cron - push dotfiles 
  ansible.builtin.cron:
    name: "push dotfiles (at 11 AM)"
    hour: "11"
    minute: "0"
    job: "cd $HOME/.dotfiles && git add . && git commit -m 'automated update' && git push origin main"

- name: cron - push neovim config 
  ansible.builtin.cron:
    name: "push neovim (at 11 AM)"
    hour: "11"
    minute: "0"
    job: "cd $HOME/.config/nvim && git add . && git commit -m 'automated update' && git push origin main"

- name: cron - delete trashed items 
  ansible.builtin.cron:
    name: "empty trash older than 30 days (every week)"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "trash-empty 30"

# ---
# systemd
# ---

- name: start docker service
  become: true
  systemd:
    state: started
    name: docker
    enabled: yes

- name: enable touchegg
  become: true
  systemd:
    state: started
    name: touchegg
    enabled: yes

# --
# spicetify
# --
- name: spotify permissions (for spicetify)
  ansible.builtin.shell: |
    sudo chmod a+wr /home/fabian/.nix-profile/share/spotify
    sudo chmod a+wr -R /home/fabian/.nix-profile/share/spotify/Apps     

# --
# xdg open
# --

- name: "Create qutebrowser desktop entry"
  ansible.builtin.copy:
    dest: $HOME/.local/share/applications/qutebrowser.desktop
    content: |
      [Desktop Entry]
      Name=qutebrowser
      Exec=qutebrowser
      Type=Application
      MimeType=x-scheme-handler/unknown;x-scheme-handler/about;x-scheme-handler/https;x-scheme-handler/http;text/html;html

- name: "Create sxiv desktop entry"
  ansible.builtin.copy:
    dest: $HOME/.local/share/applications/sxiv.desktop
    content: |
      [Desktop Entry]
      Name=sxiv
      Exec=sxiv
      Type=Application
      MimeType=image/png;image/jpeg

- name: "Create sioyek desktop entry"
  ansible.builtin.copy:
    dest: $HOME/.local/share/applications/sioyek.desktop
    content: |
      [Desktop Entry]
      Name=sioyek
      Exec=sioyek
      Type=Application
      MimeType=application/pdf

- name: "Create foliate desktop entry"
  ansible.builtin.copy:
    dest: $HOME/.local/share/applications/foliate.desktop
    content: |
      [Desktop Entry]
      Name=foliate
      Exec=foliate
      Type=Application
      MimeType=application/epub+zip
