---

- include_tasks: '{{ ansible_os_family }}.yml'

- name: clone neovim
  git:
    repo: https://github.com/fabian-gubler/nvim-config.git
    dest: "$HOME/.config/nvim"
    update: no

- name: gtk file chooser window size
  ansible.builtin.shell:
    cmd: gsettings set org.gtk.Settings.FileChooser window-size '(1200, 800)'

- name: install gotop
  ansible.builtin.shell:
    cmd: go install github.com/xxxserxxx/gotop/v4/cmd/gotop@latest

- name: install spicetify
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

- name: install sioyek
  ansible.builtin.shell: 
    cmd: $HOME/.dotfiles/roles/misc/files/get-sioyek.sh

# Spicetify permissions
- name: read/write permissions for spicetify
  ansible.builtin.file:
    path: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
    state: directory
    mode: 'a+wr'
  become: true

- name: read/write permissions for spicetify
  ansible.builtin.file:
    path: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
    state: directory
    mode: 'a+wr'
  become: true

# Cron environment
- name: Add "SHELL" environment variable to crontab
  ansible.builtin.cron:
    name: SHELL
    env: yes
    job: /bin/zsh

- name: Add "MAILTO" environment variable to crontab
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: $MAIL_ADDRESS

# Cronjobs
- name: check mail every 5 minutes
  ansible.builtin.cron:
    name: "sync mailbox"
    minute: "*/5"
    job: "killall mbsync &>/dev/null; mbsync protonmail" 

- name: backup vm every week
  ansible.builtin.cron:
    name: "backup virtual machine"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "VBoxManage export 'Win10' -o '$HOME/nextcloud/apps/vms/Win10/(date +'%Y-%m-%d')-Win10.ova'"

- name: trash downloaded files every 2 hours
  ansible.builtin.cron:
    name: "trash downloads"
    hour: "4"
    minute: "0"
    job: "trash $HOME/Downloads/*"

- name: update blacklist every week
  ansible.builtin.cron:
    name: "sync blacklist"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "$HOME/.dotfiles/scripts/utils/blacklist"

- name: push dotfiles every day
  ansible.builtin.cron:
    name: "push dotfiles"
    hour: "5"
    minute: "0"
    job: "cd $HOME/.dotfiles && git add . && git commit -m 'automated update' && git push origin main"

- name: push neovim config every day
  ansible.builtin.cron:
    name: "push neovim"
    hour: "5"
    minute: "0"
    job: "cd $HOME/.config/nvim && git add . && git commit -m 'automated update' && git push origin main"

- name: delete trashed items after 30 days
  ansible.builtin.cron:
    name: "empty trash older than 30 days every week"
    weekday: "0"
    minute: "0"
    hour: "8"
    job: "trash-empty 30"

# Sysadmin
- name: add user to docker group
  become: true
  user:
    name: 'fabian'
    groups: docker
    append: yes
