---

# Mongo db
# sudo dnf install mongodb-org-server mongodb-org-shell mongodb-database-tools mongodb-org-mongos mongodb-mongosh
# link: https://tecadmin.net/install-mongodb-on-fedora/

# ----------------
# SYSTEM
# ----------------

- name: Install automatic updates
  package:
    name: dnf-automatic
    state: present
  become: true

- name: change power button behavior
  ansible.builtin.shell: 
    cmd: grep -qxF "HandlePowerKey=suspend" /etc/systemd/logind.conf || echo "HandlePowerKey=suspend" | sudo tee -a /etc/systemd/logind.conf
  become: true

# - name: suspend on inactivity
#   ansible.builtin.shell: 
#     cmd: grep -qxF "IdleAction=suspend" /etc/systemd/logind.conf || echo "IdleAction=suspend" | sudo tee -a /etc/systemd/logind.conf

- name: set inactivity timeout
  ansible.builtin.shell: 
    cmd: grep -qxF "IdleActionSec=15min" /etc/systemd/logind.conf || echo "IdleActionSec=15min" | sudo tee -a /etc/systemd/logind.conf
  become: true

# ----------------
# Applications
# ----------------

- name: link handler binary
  become: true
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/config/handlr/handlr"
    dest: "{{ ansible_user_dir }}/.local/bin/handlr"
    state: link

- name: link handler xdg-open replacement
  become: true
  file:
    src: "{{ ansible_user_dir }}/.dotfiles/config/handlr/xdg-open"
    dest: "/usr/bin/xdg-open"
    state: link

- name: install lazydocker
  shell:
    cmd: go install github.com/jesseduffield/lazydocker@latest

- name: install lf
  shell:
    cmd: env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

# - name: extract postman tar
#   ansible.builtin.unarchive:
#     src: "{{ ansible_user_dir }}/Downloads/postman.tar.gz"
#     dest: "{{ ansible_user_dir }}/.local/share/"
#
# - name: link postman-agent
#   become: true
#   file:
#     src: "{{ ansible_user_dir }}/.local/share/Postman\ Agent/app/postman-agent"
#     dest: "{{ ansible_user_dir }}/.local/bin/postman-agent"
#     state: link

# ---
# ZSA WAlly
# ---

- name: install dependencies
  become: true
  package:
    name:
      - gtk3
      - webkit2gtk3 
      - libusb
    state: present

# 1. TODO: Download binary (https://github.com/zsa/wally/wiki/Linux-install#3-download-the-wally-binary-and-run-it)
# 2. TODO: Udev Rule (https://github.com/zsa/wally/wiki/Linux-install#2-create-a-udev-rule-file)
# 3. TODO: Make executable and put in .local/bin

# ---
# docker
# ---

- name: add docker repositories
  ansible.builtin.shell: 
    cmd: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: install docker packages
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: present

- name: add user to docker group
  become: true
  user:
    name: 'fabian'
    groups: docker
    append: yes

