---

# Mongo db
# sudo dnf install mongodb-org-server mongodb-org-shell mongodb-database-tools mongodb-org-mongos mongodb-mongosh
# link: https://tecadmin.net/install-mongodb-on-fedora/


- name: Install automatic updates
  package:
    name: dnf-automatic
    state: present
  become: true

- name: Enable automatic updates
  become: true
  systemd:
    name: tlp
    enabled: yes

- name: clone dmenu bluetooth-autoconnect
  git:
    repo: https://github.com/jrouleau/bluetooth-autoconnect
    dest: "{{ ansible_user_dir }}/.local/share/bluetooth-autoconnect"
    update: no

- name: link bluetooth-autoconnect
  become: true
  file:
    src: "{{ ansible_user_dir }}/.local/share/bluetooth-autoconnect/bluetooth-autoconnect"
    dest: "/usr/bin/bluetooth-autoconnect"
    state: link

- name: link bluetooth-autoconnect.service
  become: true
  file:
    src: "{{ ansible_user_dir }}/.local/share/bluetooth-autoconnect/bluetooth-autoconnect.service"
    dest: "/etc/systemd/user/bluetooth-autoconnect.service"
    state: link

- name: enable bluetooth-autoconnect
  systemd:
    name: bluetooth-autoconnect
    state: started
    scope: user
    enabled: yes

- name: install lazydocker
  shell:
    cmd: go install github.com/jesseduffield/lazydocker@latest


# - name: extract postman tar
#   ansible.builtin.unarchive:
#     src: "{{ ansible_user_dir }}/Downloads/postman.tar.gz"
#     dest: "{{ ansible_user_dir }}/.local/share/"
#
# - name: link postman-agent
#   become: true
#   file:
#     src: "{{ ansible_user_dir }}/.local/share/Postman\ Agent/app/postman-agent"
#     dest: "{{ ansible_user_dir }}/.local/bin/postman-agent"
#     state: link
      
# ---
# docker
# ---

- name: add docker repositories
  ansible.builtin.shell: 
    cmd: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: install docker packages
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: present

- name: Enable automatic updates
  become: true
  systemd:
    state: started
    name: docker
    enabled: yes
