#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import Current Theme
ROFI_DIR=$HOME/.dotfiles/config/rofi/menu/
theme="$ROFI_DIR/shared/style-2.rasi"

# Layout
list_col='4'
list_row='2'

# Options
option_1=" Back"
option_2="0%"
option_3="2%"
option_4="100%"
option_5="-10%"
option_6="+10%"

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'window {border: 0px solid; border-color: #FFF; background-color: transparent; location: center; anchor: center; fullscreen: false; width: 600;}' \
		-theme-str 'element {border: 2px solid; padding: 20px; border-color: #4C566A; margin: 0px;}' \
		-theme-str 'mainbox {padding: 0px; background: transparent;}' \
		-theme-str 'element selected.normal {background-color: @background; text-color: #FFFFFF;}' \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		sleep 0.2
		$ROFI_DIR/settings
	elif [[ "$1" == '--opt2' ]]; then
		brightnessctl set 0%
		$ROFI_DIR/submenu/brightness
	elif [[ "$1" == '--opt3' ]]; then
		brightnessctl set 2%
		$ROFI_DIR/submenu/brightness
	elif [[ "$1" == '--opt4' ]]; then
		brightnessctl set 100%
		$ROFI_DIR/submenu/brightness
	elif [[ "$1" == '--opt5' ]]; then
		brightnessctl set 10%-
		$ROFI_DIR/submenu/brightness
	elif [[ "$1" == '--opt6' ]]; then
		brightnessctl set 10%+
		$ROFI_DIR/submenu/brightness
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac

